### ISSUE TITLE
please make a new release to pypi!

### ISSUE THREAD

**Issue by whitmo** [msabramo/python_dotted_name_resolver#3]

**Comment by msabramo** [comment]
Done.

https://pypi.python.org/pypi/dotted_name_resolver/0.1

Better late than never? :smile:

**Comment by whitmo** [comment]
you rock! thank you.

On Wed, Jan 20, 2016 at 1:22 AM, Marc Abramowitz notifications@github.com
wrote:

> Done.
> 
> https://pypi.python.org/pypi/dotted_name_resolver/0.1
> 
> Better late than never? [image: :smile:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/msabramo/python_dotted_name_resolver/issues/3#issuecomment-173116832
> .

## 

<=>
david "whit" morriss

 "If you don't know where you are,
  you don't know anything at all"

  Dr. Edgar Spencer, Ph.D., 1995
